"""内置 seed 数据集：离线演示 / 单元测试用（不访问网络）。

字段与 models.dataset.DatasetRecord 基本一致（bands 可为字符串列表或 dict 列表）。
数值基于官方 GEE 数据集的公开元数据（近似），仅供演示搜索与排序逻辑。
"""

#: 内置数据集清单
SEED_DATASETS: list[dict] = [
    {
        "id": "MODIS/061/MOD13Q1",
        "name": "MOD13Q1.061 Terra Vegetation Indices 16-Day Global 250m",
        "type": "ImageCollection",
        "description": "The MOD13Q1 V6.1 product provides a Vegetation Index (VI) value "
                       "at a per pixel basis. Two primary vegetation layers: NDVI and EVI.",
        "provider": "NASA LP DAAC at the USGS EROS Center",
        "platform": "Terra",
        "sensor": "MODIS",
        "start_date": "2000-02-18",
        "end_date": None,
        "cadence_days": 16,
        "temporal_resolution": "16-day",
        "spatial_resolution": 250,
        "coverage": "global",
        "bands": [
            {"name": "NDVI", "description": "Normalized Difference Vegetation Index", "scale": 0.0001},
            {"name": "EVI", "description": "Enhanced Vegetation Index", "scale": 0.0001},
            {"name": "DetailedQA", "description": "VI quality indicators"},
        ],
        "tags": ["evi", "ndvi", "modis", "terra", "vegetation", "vegetation-indices", "16-day", "global"],
    },
    {
        "id": "MODIS/061/MYD13Q1",
        "name": "MYD13Q1.061 Aqua Vegetation Indices 16-Day Global 250m",
        "type": "ImageCollection",
        "description": "The MYD13Q1 V6.1 product provides Vegetation Index (VI) values "
                       "from the Aqua platform. NDVI and EVI layers.",
        "provider": "NASA LP DAAC at the USGS EROS Center",
        "platform": "Aqua",
        "sensor": "MODIS",
        "start_date": "2002-07-04",
        "end_date": None,
        "cadence_days": 16,
        "temporal_resolution": "16-day",
        "spatial_resolution": 250,
        "coverage": "global",
        "bands": [
            {"name": "NDVI", "description": "Normalized Difference Vegetation Index", "scale": 0.0001},
            {"name": "EVI", "description": "Enhanced Vegetation Index", "scale": 0.0001},
        ],
        "tags": ["evi", "ndvi", "modis", "aqua", "vegetation", "vegetation-indices", "16-day", "global"],
    },
    {
        "id": "MODIS/061/MOD13A1",
        "name": "MOD13A1.061 Terra Vegetation Indices 16-Day Global 500m",
        "type": "ImageCollection",
        "description": "The MOD13A1 V6.1 product provides Vegetation Index (VI) values "
                       "at 500m spatial resolution.",
        "provider": "NASA LP DAAC at the USGS EROS Center",
        "platform": "Terra",
        "sensor": "MODIS",
        "start_date": "2000-02-18",
        "end_date": None,
        "cadence_days": 16,
        "temporal_resolution": "16-day",
        "spatial_resolution": 500,
        "coverage": "global",
        "bands": [
            {"name": "NDVI", "scale": 0.0001},
            {"name": "EVI", "scale": 0.0001},
        ],
        "tags": ["evi", "ndvi", "modis", "vegetation", "16-day", "global"],
    },
    {
        "id": "MODIS/061/MOD13A2",
        "name": "MOD13A2.061 Terra Vegetation Indices 16-Day Global 1km",
        "type": "ImageCollection",
        "description": "The MOD13A2 V6.1 product provides Vegetation Index (VI) values "
                       "at 1km spatial resolution. NDVI and EVI layers.",
        "provider": "NASA LP DAAC at the USGS EROS Center",
        "platform": "Terra",
        "sensor": "MODIS",
        "start_date": "2000-02-18",
        "end_date": None,
        "cadence_days": 16,
        "temporal_resolution": "16-day",
        "spatial_resolution": 1000,
        "coverage": "global",
        "bands": [
            {"name": "NDVI", "description": "Normalized Difference Vegetation Index", "scale": 0.0001},
            {"name": "EVI", "description": "Enhanced Vegetation Index", "scale": 0.0001},
        ],
        "tags": ["evi", "ndvi", "modis", "vegetation", "16-day", "1km", "global"],
    },
    {
        "id": "MODIS/061/MOD09GA",
        "name": "MOD09GA.061 Terra Surface Reflectance Daily Global 500m",
        "type": "ImageCollection",
        "description": "The MOD09GA V6.1 product provides an estimate of the surface "
                       "spectral reflectance of Terra MODIS bands 1-7 at 500m resolution "
                       "and corrected for atmospheric conditions. Daily.",
        "provider": "NASA LP DAAC at the USGS EROS Center",
        "platform": "Terra",
        "sensor": "MODIS",
        "start_date": "2000-02-24",
        "end_date": None,
        "cadence_days": 1,
        "temporal_resolution": "daily",
        "spatial_resolution": 500,
        "coverage": "global",
        "bands": [
            {"name": "sur_refl_b01", "description": "Surface reflectance band 1", "scale": 0.0001},
            {"name": "sur_refl_b02", "description": "Surface reflectance band 2", "scale": 0.0001},
            {"name": "sur_refl_b03", "description": "Surface reflectance band 3", "scale": 0.0001},
            {"name": "sur_refl_b04", "description": "Surface reflectance band 4", "scale": 0.0001},
        ],
        "tags": ["modis", "surface reflectance", "daily", "terra", "global"],
    },
    {
        "id": "MODIS/061/MYD09GA",
        "name": "MYD09GA.061 Aqua Surface Reflectance Daily Global 500m",
        "type": "ImageCollection",
        "description": "The MYD09GA V6.1 product provides surface spectral reflectance "
                       "from Aqua MODIS bands 1-7 at 500m resolution. Daily.",
        "provider": "NASA LP DAAC at the USGS EROS Center",
        "platform": "Aqua",
        "sensor": "MODIS",
        "start_date": "2002-07-04",
        "end_date": None,
        "cadence_days": 1,
        "temporal_resolution": "daily",
        "spatial_resolution": 500,
        "coverage": "global",
        "bands": [
            {"name": "sur_refl_b01"},
            {"name": "sur_refl_b02"},
        ],
        "tags": ["modis", "surface reflectance", "daily", "aqua", "global"],
    },
    {
        "id": "MODIS/061/MOD11A1",
        "name": "MOD11A1.061 Terra Land Surface Temperature and Emissivity Daily Global 1km",
        "type": "ImageCollection",
        "description": "The MOD11A1 V6.1 product provides daily land surface temperature "
                       "and emissivity values at 1km resolution.",
        "provider": "NASA LP DAAC at the USGS EROS Center",
        "platform": "Terra",
        "sensor": "MODIS",
        "start_date": "2000-02-24",
        "end_date": None,
        "cadence_days": 1,
        "temporal_resolution": "daily",
        "spatial_resolution": 1000,
        "coverage": "global",
        "bands": [
            {"name": "LST_Day_1km", "description": "Daytime land surface temperature", "scale": 0.02},
            {"name": "LST_Night_1km", "description": "Nighttime land surface temperature", "scale": 0.02},
            {"name": "Emis_31", "description": "Band 31 emissivity"},
            {"name": "Emis_32", "description": "Band 32 emissivity"},
        ],
        "tags": ["lst", "land surface temperature", "modis", "temperature", "daily", "1km", "global"],
    },
    {
        "id": "MODIS/061/MYD11A2",
        "name": "MYD11A2.061 Aqua Land Surface Temperature and Emissivity 8-Day Global 1km",
        "type": "ImageCollection",
        "description": "The MYD11A2 V6.1 product provides 8-day composite land surface "
                       "temperature and emissivity from Aqua MODIS at 1km.",
        "provider": "NASA LP DAAC at the USGS EROS Center",
        "platform": "Aqua",
        "sensor": "MODIS",
        "start_date": "2002-07-04",
        "end_date": None,
        "cadence_days": 8,
        "temporal_resolution": "8-day",
        "spatial_resolution": 1000,
        "coverage": "global",
        "bands": [
            {"name": "LST_Day_1km", "description": "Daytime land surface temperature", "scale": 0.02},
            {"name": "LST_Night_1km", "description": "Nighttime land surface temperature", "scale": 0.02},
        ],
        "tags": ["lst", "land surface temperature", "modis", "temperature", "8-day", "1km", "global"],
    },
    {
        "id": "NASA/GLDAS/V021/NOAH/G025/T3H",
        "name": "GLDAS-2.1 Noah Land Surface Model L4 3 Hourly 0.25 x 0.25 degree",
        "type": "ImageCollection",
        "description": "GLDAS-2.1 Noah land surface model output at 0.25 degree, 3-hourly. "
                       "Includes soil moisture, temperature, and evapotranspiration.",
        "provider": "NASA GSFC",
        "platform": "GLDAS",
        "sensor": "Model",
        "start_date": "2000-01-01",
        "end_date": None,
        "cadence_days": 1,
        "temporal_resolution": "daily",
        "spatial_resolution": 27830,
        "coverage": "global",
        "bands": [
            {"name": "SoilMoi0_10cm_inst", "description": "Soil moisture 0-10 cm", "scale": 0.001},
            {"name": "SoilMoi10_40cm_inst", "description": "Soil moisture 10-40 cm", "scale": 0.001},
            {"name": "SoilTMP0_10cm_inst", "description": "Soil temperature 0-10 cm", "scale": 0.01},
            {"name": "Evap_tavg", "description": "Evapotranspiration", "scale": 0.00001},
            {"name": "Tair_f_inst", "description": "Air temperature", "scale": 0.01},
        ],
        "tags": ["soil moisture", "sm", "gldas", "land surface model", "3-hourly", "0.25 degree", "global"],
    },
    {
        "id": "NASA/GIBS/terra",
        "name": "NASA Terra Satellite Imagery (GIBS)",
        "type": "ImageCollection",
        "description": "Real-time Terra satellite imagery from NASA GIBS.",
        "provider": "NASA GIBS",
        "platform": "Terra",
        "sensor": "MODIS",
        "start_date": "2015-10-01",
        "end_date": None,
        "spatial_resolution": 250,
        "coverage": "global",
        "bands": [
            {"name": "B1"},
            {"name": "B2"},
        ],
        "tags": ["imagery", "terra", "nasa", "global"],
    },
    {
        "id": "UCSB-CHG/CHIRPS/DAILY",
        "name": "CHIRPS Daily Precipitation 0.05 degree",
        "type": "ImageCollection",
        "description": "CHIRPS (Climate Hazards Group InfraRed Precipitation with Station "
                       "data) daily precipitation at 0.05 degree resolution.",
        "provider": "UCSB Climate Hazards Group",
        "platform": "CHIRPS",
        "sensor": "Satellite+Station",
        "start_date": "1981-01-01",
        "end_date": None,
        "cadence_days": 1,
        "temporal_resolution": "daily",
        "spatial_resolution": 5566,
        "coverage": "global",
        "bands": [
            {"name": "precipitation", "description": "Precipitation", "scale": 1.0},
        ],
        "tags": ["precipitation", "rainfall", "chirps", "daily", "global"],
    },
    {
        "id": "COPERNICUS/S2_SR_HARMONIZED",
        "name": "Sentinel-2 MSI MultiSpectral Instrument, Level-2A, 10m",
        "type": "ImageCollection",
        "description": "Sentinel-2 MSI Level-2A surface reflectance, 10m resolution. "
                       "Spatial resolution 10m/20m/60m depending on band.",
        "provider": "European Commission / ESA",
        "platform": "Sentinel-2",
        "sensor": "MSI",
        "start_date": "2017-03-28",
        "end_date": None,
        "cadence_days": 5,
        "temporal_resolution": "8-day",
        "spatial_resolution": 10,
        "coverage": "global",
        "bands": [
            {"name": "B2", "description": "Blue", "scale": 0.0001},
            {"name": "B3", "description": "Green", "scale": 0.0001},
            {"name": "B4", "description": "Red", "scale": 0.0001},
            {"name": "B8", "description": "NIR", "scale": 0.0001},
        ],
        "tags": ["sentinel-2", "msi", "10m", "surface reflectance", "global"],
    },
    {
        "id": "ECMWF/ERA5_LAND/MONTHLY_AGGR",
        "name": "ERA5-Land Monthly Aggregated - ECMWF Climate Reanalysis",
        "type": "ImageCollection",
        "description": "ERA5-Land monthly aggregated reanalysis data at ~9km resolution. "
                       "Includes temperature, soil moisture, and evapotranspiration.",
        "provider": "ECMWF / Copernicus",
        "platform": "ERA5-Land",
        "sensor": "Reanalysis",
        "start_date": "1950-01-01",
        "end_date": None,
        "cadence_days": 30,
        "temporal_resolution": "monthly",
        "spatial_resolution": 11132,
        "coverage": "global",
        "bands": [
            {"name": "temperature_2m", "description": "2m temperature", "scale": 0.1},
            {"name": "total_precipitation", "description": "Total precipitation", "scale": 0.001},
            {"name": "volumetric_soil_water_layer_1", "description": "Soil moisture layer 1", "scale": 0.001},
        ],
        "tags": ["era5", "reanalysis", "soil moisture", "temperature", "monthly", "9km", "global"],
    },
]
